### ISSUE TITLE
1st example - how 2 require krokus?

### ISSUE THREAD

**Issue by sebastianrothbucher** [klyrr/krokus#4]
most probably I'm just not getting something - but maybe you can clarify it anyway: assume I switch into an empty directory, `npm install krokus` there and create a test.js with line 23ff from the README.md and run it via `node test.js`

It will work when I either change 

``` javascript
const krokus = require('krokus');
```

to

``` javascript
const krokus = require('krokus').krokus;
```

or change

``` javascript
krokus.formatCurrency(10000, formatCurrencyPattern)
```

to

``` javascript
krokus.krokus.formatCurrency(10000, formatCurrencyPattern)
```

(in fact, I did `console.log(krokus.krokus.formatCurrency(10000, formatCurrencyPattern)`)

Again: it's most probably me - so thanks!!!

**Comment by klyrr** [comment]
You were totally right. I fixed this in the `index.js` and just published it. So with version `0.2.1` the export should work as expected.
Thanks for finding this :)

**Comment by sebastianrothbucher** [comment]
works like charm - thx so much! Wish I found out about krokus before going nuts over toLocaleString() - at least I know now though
